### ISSUE TITLE
What is the update time?

### ISSUE THREAD

**Issue by Scaledish** [MaxKorlaar/hypixel-signatures#37]
My xp to next level is sitting at about 60k, when in reality it is 30k. how often do they update?

**Comment by MaxKorlaar** [comment]
Hey, I'm assuming that your username is Scaledish as well?

On my site that'd generate the following image:

![](https://hypixel.paniek.de/signature/a7483027338b40a1b1d2a1829f13d578/general-tooltip)

Is it correct on my site, but not on the forums? If so, then that's because the Hypixel Forums caches all external images for about 1 day. Unfortunately, I have no control over this. On my site, I update everything about every 10 minutes.

If it's still not correct on my site, then that'd be a bug with my code and I'll be glad to resolve it!

**Comment by Scaledish** [comment]
Oh, thanks! that could be it indeed, the forums cathing the image. it appers correct on your site. thanks for confirming!

**Comment by MaxKorlaar** [comment]
No problem, glad I could help!
