### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NexoWolf** [MaxKorlaar/hypixel-signatures#46]
**Describe the bug**
Page won't load half of the guild members (50/102), and yes, I have tried waiting for a good ammount of minutes. No, I do not have connection issues.
**To Reproduce**
1.-look for guild members
**Expected behavior**
I expected the page to load the whole list xd

**Screenshots**
https://imgur.com/a/Re0S6Ji

**Desktop (please complete the following information):**
- chrome, windows 10

**Additional context**
Thanks for reading 👍

**Comment by MaxKorlaar** [comment]
Thanks for reporting this issue to me, that certainly isn't expected behaviour. I can see that there are about 150.000 jobs (tasks to load guild member data or player data in a friends list) left in the queue on my site, which is obviously too much, as I have limited it to handle only 750 per minute and drop the rest. I'll see if I can speed up this process!

**Comment by MaxKorlaar** [comment]
I have cleared the queue, you should now be able to look up guild statistics again 👍🏻 !
